require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PtosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pto. As you add validations to Pto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PtosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ptos as @ptos" do
      pto = Pto.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ptos)).to eq([pto])
    end
  end

  describe "GET show" do
    it "assigns the requested pto as @pto" do
      pto = Pto.create! valid_attributes
      get :show, {:id => pto.to_param}, valid_session
      expect(assigns(:pto)).to eq(pto)
    end
  end

  describe "GET new" do
    it "assigns a new pto as @pto" do
      get :new, {}, valid_session
      expect(assigns(:pto)).to be_a_new(Pto)
    end
  end

  describe "GET edit" do
    it "assigns the requested pto as @pto" do
      pto = Pto.create! valid_attributes
      get :edit, {:id => pto.to_param}, valid_session
      expect(assigns(:pto)).to eq(pto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pto" do
        expect {
          post :create, {:pto => valid_attributes}, valid_session
        }.to change(Pto, :count).by(1)
      end

      it "assigns a newly created pto as @pto" do
        post :create, {:pto => valid_attributes}, valid_session
        expect(assigns(:pto)).to be_a(Pto)
        expect(assigns(:pto)).to be_persisted
      end

      it "redirects to the created pto" do
        post :create, {:pto => valid_attributes}, valid_session
        expect(response).to redirect_to(Pto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pto as @pto" do
        post :create, {:pto => invalid_attributes}, valid_session
        expect(assigns(:pto)).to be_a_new(Pto)
      end

      it "re-renders the 'new' template" do
        post :create, {:pto => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pto" do
        pto = Pto.create! valid_attributes
        put :update, {:id => pto.to_param, :pto => new_attributes}, valid_session
        pto.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pto as @pto" do
        pto = Pto.create! valid_attributes
        put :update, {:id => pto.to_param, :pto => valid_attributes}, valid_session
        expect(assigns(:pto)).to eq(pto)
      end

      it "redirects to the pto" do
        pto = Pto.create! valid_attributes
        put :update, {:id => pto.to_param, :pto => valid_attributes}, valid_session
        expect(response).to redirect_to(pto)
      end
    end

    describe "with invalid params" do
      it "assigns the pto as @pto" do
        pto = Pto.create! valid_attributes
        put :update, {:id => pto.to_param, :pto => invalid_attributes}, valid_session
        expect(assigns(:pto)).to eq(pto)
      end

      it "re-renders the 'edit' template" do
        pto = Pto.create! valid_attributes
        put :update, {:id => pto.to_param, :pto => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pto" do
      pto = Pto.create! valid_attributes
      expect {
        delete :destroy, {:id => pto.to_param}, valid_session
      }.to change(Pto, :count).by(-1)
    end

    it "redirects to the ptos list" do
      pto = Pto.create! valid_attributes
      delete :destroy, {:id => pto.to_param}, valid_session
      expect(response).to redirect_to(ptos_url)
    end
  end

end
